version: '3.9'

services:
    spring-boot:
        image: spring-boot
        build:
          context: ./${APPLICATION_ROOT_FOLDER}
        ports:
          - "${LOCAL_PORT}:${SERVER_PORT}"
          - "5005:5005"
        depends_on:
            - db
        environment: 
          SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
          SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
          SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
          SERVER_PORT: ${SERVER_PORT}
        volumes:
          - ${APPLICATION_ROOT_FOLDER}:/usr/src/mymaven

    db:
        container_name: mysqldatabase
        image: mysql:8.0.22
        ports:
            - "${MYSQL_PORT}:3306"
        command: ["--default-authentication-plugin=mysql_native_password"]
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./DockerData/db:/var/lib/mysql
        expose:
            - 3306
        restart: always
